### PR TITLE
Document reader view controller now adheres to safe area constraints

### PR DESCRIPTION
**Pull request by JRR-OSU**
Fixed the UI code here to force the views to be laid out within safe area bounds. This improves use on iPad Pro and iPhone X/R/S.

### CODE REVIEW

**Comment by ivobrands** [comment]
When will this feature be available

**Comment by JRR-OSU** [comment]
> When will this feature/update be available

Just need it merged! You can also integrate yourself fairly easily.

**Comment by ivobrands** [comment]
Yes i did, Thank you, good work!

**Comment by regnete** [comment]
thx for contributing. just releases v0.9.11 containing your improvements.

**Pull request merged**
